if Code.ensure_loaded?(Postgrex) do
  defmodule LegionWeb.AgentTracker.Postgres do
    @moduledoc """
    Tracks Legion agents from a PostgreSQL-backed `Legion.Store`.

    This tracker rebuilds the dashboard from persisted conversations, so agents
    remain visible after their processes or the application stop. It also listens
    for PostgreSQL notifications and publishes live dashboard updates without
    polling.

    ## Usage

    Define a `Legion.Store.Postgres` store and configure it for Legion:

        defmodule MyApp.AgentStore do
          use Legion.Store.Postgres, repo: MyApp.Repo
        end

        config :legion, :store, MyApp.AgentStore

    Configure LegionWeb to use it:

        config :legion_web, :agent_tracker,
          {LegionWeb.AgentTracker.Postgres, store: MyApp.AgentStore}

    ## Requirements

    The configured store must implement `Legion.Store` and expose the
    `__repo__/0` and `__table__/0` functions generated by
    `Legion.Store.Postgres`. The host application must provide an Ecto repo
    backed by `Ecto.Adapters.Postgres` and include Postgrex.

    ## Tracking behavior

    The tracker loads up to 100 persisted conversations. It resolves each
    `agent_id` through `Legion.lookup/1` to distinguish live agents from stopped
    ones, and reconstructs durable user, assistant, eval-result, and error events
    from the stored conversation.

    PostgreSQL notifications reload the affected conversation and broadcast its
    current status and usage. Historical events are loaded when an agent is
    opened; later notifications broadcast only newly appended events.

    Usage comes from the store's `usage` column, which Legion appends to at the
    end of each turn, so usage updates arrive per turn rather than per request.

    An agent's identity is the store's `ratelimit_metadata` column: the merged
    identity of the rate-limit rules the agent was started with, written by
    `Legion.RateLimiter.Postgres` before its first turn. Agents started without
    rate limiting have no identity.
    """

    use GenServer

    @behaviour LegionWeb.AgentTracker

    alias LegionWeb.AgentTracker.{LegionAgent, LegionEvent}

    def start_link(opts \\ []) do
      GenServer.start_link(__MODULE__, opts, name: __MODULE__)
    end

    @impl true
    def init(opts) do
      store = Keyword.fetch!(opts, :store)
      validate_store!(store)

      notifications_module = Keyword.get(opts, :notifications, Postgrex.Notifications)

      {:ok, notifications} =
        notifications_module.start_link(store.__repo__().config() ++ [auto_reconnect: true])

      {:ok, _ref} = notifications_module.listen(notifications, store.__table__())

      {:ok, %{store: store, notifications: notifications, event_cursors: %{}}}
    end

    @impl LegionWeb.AgentTracker
    def list_agents(limit) do
      GenServer.call(__MODULE__, {:list_agents, limit})
    end

    @impl LegionWeb.AgentTracker
    def get_agent(agent_id) do
      GenServer.call(__MODULE__, {:get_agent, agent_id})
    end

    @impl LegionWeb.AgentTracker
    def get_events(agent_id) do
      GenServer.call(__MODULE__, {:get_events, agent_id})
    end

    @impl LegionWeb.AgentTracker
    def get_usage(agent_id) do
      GenServer.call(__MODULE__, {:get_usage, agent_id})
    end

    @impl true
    def handle_call({:list_agents, limit}, _from, state) do
      agents = state.store.list(limit) |> Enum.map(&to_record/1)
      {:reply, agents, state}
    end

    def handle_call({:get_agent, agent_id}, _from, state) do
      agent =
        case state.store.get(agent_id) do
          {:ok, payload} -> to_record(payload)
          :error -> nil
        end

      {:reply, agent, state}
    end

    def handle_call({:get_events, agent_id}, _from, state) do
      events = load_events(state.store, agent_id)
      {:reply, events, put_in(state.event_cursors[agent_id], length(events))}
    end

    def handle_call({:get_usage, agent_id}, _from, state) do
      usage =
        case state.store.get(agent_id) do
          {:ok, payload} -> to_usage(payload)
          :error -> []
        end

      {:reply, usage, state}
    end

    @impl true
    def handle_info({:notification, _pid, _ref, _channel, agent_id}, state) do
      case state.store.get(agent_id) do
        {:ok, payload} ->
          record = to_record(payload)
          events = to_events(payload)

          Phoenix.PubSub.broadcast(
            LegionWeb.PubSub,
            "legion_web:agents",
            {record.status, agent_id, record}
          )

          broadcast_usage(agent_id, to_usage(payload))

          case Map.fetch(state.event_cursors, agent_id) do
            {:ok, cursor} ->
              events
              |> Enum.drop(cursor)
              |> Enum.each(&broadcast_event(agent_id, &1))

            :error ->
              :ok
          end

          state = put_in(state.event_cursors[agent_id], length(events))
          {:noreply, state}

        :error ->
          # The conversation is gone from the store; drop its cursor too.
          {:noreply, update_in(state.event_cursors, &Map.delete(&1, agent_id))}
      end
    end

    def handle_info(_message, state), do: {:noreply, state}

    defp validate_store!(store) do
      if Code.ensure_loaded?(store) and function_exported?(store, :__repo__, 0) and
           function_exported?(store, :__table__, 0) do
        :ok
      else
        raise ArgumentError,
              "Postgres tracker store #{inspect(store)} must expose __repo__/0 and __table__/0"
      end
    end

    defp load_events(store, agent_id) do
      case store.get(agent_id) do
        {:ok, payload} -> to_events(payload)
        :error -> []
      end
    end

    defp to_record(payload) do
      {pid, running?} =
        case Legion.lookup(payload.agent_id) do
          {:ok, pid} -> {pid, Legion.running?(pid)}
          :error -> {nil, false}
        end

      %LegionAgent{
        agent_id: payload.agent_id,
        parent_agent_id: payload.parent_agent_id,
        agent_module: payload.agent_module,
        pid: pid,
        status: status(running?, payload.status),
        identity: Map.get(payload, :ratelimit_metadata),
        started_at: to_milliseconds(payload.started_at),
        finished_at: nil,
        task: nil,
        iterations: 0
      }
    end

    # A stored :running status without a live local process means the process
    # died mid-turn. An idle stored status belongs to a completed run.
    defp status(true, :running), do: :running
    defp status(true, _idle_or_nil), do: :idle
    defp status(false, :running), do: :dead
    defp status(false, _idle_or_nil), do: :done

    defp to_milliseconds(nil), do: nil

    defp to_milliseconds(%NaiveDateTime{} = value) do
      value
      |> DateTime.from_naive!("Etc/UTC")
      |> DateTime.to_unix(:millisecond)
    end

    defp to_events(%{conversation_state: %{messages: messages}, agent_id: agent_id} = payload) do
      # Later entries win: a turn that crashed under :turn persistence keeps its
      # usage while its messages are lost, and the next turn reuses the same slots.
      usage_by_index = Map.new(to_usage(payload), &{&1["message_index"], &1})

      for {message, seq} <- Enum.with_index(messages, 1) do
        to_event(message, seq, agent_id, usage_by_index[seq - 1])
      end
    end

    defp to_events(_payload), do: []

    defp to_usage(%{usage: usage}) when is_list(usage), do: usage
    defp to_usage(_payload), do: []

    defp to_event(message, seq, agent_id, usage) do
      %LegionEvent{
        seq: seq,
        agent_id: agent_id,
        type: event_type(message.type),
        timestamp: message[:at],
        data: event_data(message.type, message.content, usage)
      }
    end

    defp event_type(:user), do: :message_start
    defp event_type(:assistant), do: :llm_stop
    defp event_type(_eval_result_or_error), do: :eval_stop

    defp event_data(:user, content, _usage), do: %{message: content}

    defp event_data(:assistant, content, usage) do
      object =
        case content do
          content when is_binary(content) ->
            case Jason.decode(content) do
              {:ok, object} -> object
              {:error, _reason} -> %{"raw" => content}
            end

          content ->
            %{"raw" => inspect(content)}
        end

      if usage, do: %{object: object, usage: usage}, else: %{object: object}
    end

    defp event_data(:eval_result, content, _usage), do: %{success: true, result: content}
    defp event_data(:error, content, _usage), do: %{success: false, error: content}

    defp broadcast_usage(agent_id, usage) do
      Phoenix.PubSub.broadcast(
        LegionWeb.PubSub,
        "legion_web:agent:#{inspect(agent_id)}",
        {:usage, agent_id, usage}
      )
    end

    defp broadcast_event(agent_id, event) do
      Phoenix.PubSub.broadcast(
        LegionWeb.PubSub,
        "legion_web:agent:#{inspect(agent_id)}",
        {:new_event, event}
      )
    end
  end
end
